# This is a Kubernetes Secret configuration file. It defines a Secret resource named "cloudship-secret" in the "cloudship" namespace. The Secret contains a single key-value pair, where the key is "DUMMY_SECRET" and the value is "prod-secret". You can apply this configuration to your Kubernetes cluster using the command `kubectl apply -f k8s/secret.yaml`.

apiVersion: v1
kind: Secret
metadata:
  name: cloudship-secret
  namespace: cloudship
type: Opaque
stringData:
  DUMMY_SECRET: prod-secret
